channels:
- conda-forge
- defaults
dependencies:
- python=2.7
- tensorflow=1.4.0 # Must list before keras to preempt default keras backend
- bokeh
- cython
- future
- h5py
- ipython
- ipyparallel
- jupyter
- keras=2.1.5
- matplotlib=2.0.2
- nose
- numpy
- opencv
- peakutils
- scipy
- scikit-image
- scikit-learn
- spyder=3.1
- tifffile
- tqdm
