channels:
- conda-forge
- defaults
dependencies:
- python <=3.12
- av
- cython
- future
- h5py
- holoviews >=1.16.2
- ipyparallel
- ipywidgets
- matplotlib
- moviepy
- numpy <2.0.0
- numpydoc
- opencv
- peakutils
- psutil
- pynwb
- scikit-image >=0.19.0
- scikit-learn >=1.2
- scipy >= 1.10.1
- tensorflow >=2.4.0
- tifffile
- tqdm
- zarr
