channels:
- conda-forge
dependencies:
- python >=3.10
- bokeh
- coverage
- cython
- h5py
- holoviews =1.15.2
- ipykernel
- ipython
- ipyparallel
- jupyter
- matplotlib
- mypy
- nose
- numpy
- numpydoc
- opencv
- peakutils
- pims
- psutil
- pynwb
- pyqtgraph
- scikit-image >=0.19.0
- scikit-learn >=1.2
- scipy >= 1.10.1
- tensorflow >= 2.4.0
- tifffile
- tk
- tqdm
- yapf
- z5py >= 2.0.15
