channels:
- conda-forge
dependencies:
- python >=3.9
- bokeh
- coverage
- cython
- future
- h5py >=2.10.0,<3
- holoviews
- ipykernel
- ipython
- ipyparallel
- jupyter
- matplotlib
- mypy
- nose
- numpy
- numpydoc
- opencv
- peakutils
- pims
- psutil
- pynwb
- pyqtgraph
- scikit-image >=0.19.0
- scikit-learn
- scipy
- tensorflow
- tifffile
- tk
- tqdm
- yapf
- z5py
