channels:
- conda-forge
dependencies:
- python >=3.7
- bokeh
- coverage
- cython
- future
- h5py >=2.10.0,<3
- holoviews
- ipykernel
- ipython
- ipyparallel
- jupyter
- matplotlib
- mypy
- nose
- numpy
- numpydoc
- opencv
- peakutils
- pims
- psutil
- pynwb==1.4.0
- pyqtgraph
- scikit-image
- scikit-learn
- scipy
- spyder
- tensorflow==2.4.1
- tensorflow-addons==0.12.1
- tifffile
- tk
- tqdm
- yapf
