channels:
- conda-forge
- defaults
dependencies:
- python <=3.12
- av
- cython
- h5py >=3.4.0
- holoviews >=1.16.2
- ipython
- ipyparallel
- ipywidgets
- matplotlib
- moviepy
- nose
- numpy <2.0.0,>=1.26
- numpydoc
- opencv
- peakutils >=1.3.5
- pims
- psutil
- pynwb
- scikit-image >=0.19.0
- scikit-learn >=1.2
- scipy >= 1.10.1
- tensorflow >=2.4.0,<2.16
- tifffile
- tqdm
- zarr
